resources:
  pipelines:
  - pipeline: build
    source: 'Python packaging pipeline'
    trigger: true 
    
jobs:
- job: Linux_Test
  timeoutInMinutes: 60
  variables:
    skipComponentGovernanceDetection: true
  workspace:
    clean: all
  pool: Linux-CPU  
  steps:
  - task: DownloadPipelineArtifact@2
    displayName: 'Download Pipeline Artifact'
    inputs:
      preferTriggeringPipeline: true      
      artifactName: 'drop-linux-cpu-x86_64'
      targetPath: '$(Build.BinariesDirectory)/Release'
      runVersion: 'latest'
      buildType: specific
      project: '530acbc4-21bc-487d-8cd8-348ff451d2ff'
      definition: 841
      buildVersionToDownload: specific
      pipelineId: 227749
    
  - task: DownloadPipelineArtifact@2
    displayName: 'Download Pipeline Artifact'
    inputs:
      #buildType: 'current'
      artifactName: 'onnxruntime'
      targetPath: '$(Build.BinariesDirectory)/whl'
      buildType: specific
      project: '530acbc4-21bc-487d-8cd8-348ff451d2ff'
      definition: 841
      buildVersionToDownload: specific
      pipelineId: 227749


  - task: Bash@3
    displayName: 'Bash Script'
    inputs:
      targetType: filePath
      filePath: tools/ci_build/github/linux/run_python_tests.sh

  - template: templates/clean-agent-build-directory-step.yml