resources:
  pipelines:
  - pipeline: build
    source: 'Python packaging pipeline'
    trigger: true 
    
jobs:
- job: Linux_Test
  timeoutInMinutes: 60
  variables:
    skipComponentGovernanceDetection: true
  workspace:
    clean: all
  pool: Linux-CPU  
  steps:
  - task: PowerShell@2
    displayName: 'Add Build Tag'
    #Run this step only if all previous steps are succeeded and (this build was triggered by a resource trigger or it was triggered by another build).
    condition: and(succeeded(), eq(variables['Build.Reason'], 'ResourceTrigger'))
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    inputs:
      targetType: inline
      script: |
        $headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
        $headers.Add("Authorization", "Bearer $env:SYSTEM_ACCESSTOKEN")
        $headers.Add("Content-Type", "application/json")
        Write-Host "##vso[task.logissue type=warning]$Env:BUILD_TRIGGEREDBY_BUILDID"
        $uri = "https://dev.azure.com/aiinfra/Lotus/_apis/build/builds/$Env:BUILD_TRIGGEREDBY_BUILDID/tags/test%20pass?api-version=6.0"
        Write-Host "##vso[task.logissue type=warning]$uri"
        Invoke-RestMethod -Uri $uri -Headers $headers -Method PUT

  - task: mspremier.PostBuildCleanup.PostBuildCleanup-task.PostBuildCleanup@3
    displayName: 'Clean Agent Directories'
    condition: always()
