jobs:
parameters:
- name: RunOnnxRuntimeTests
  displayName: Run Tests?
  type: boolean
  default: true



stages:
- stage: cuda
  dependsOn: []
  jobs:
  - template: templates/win-gpu-ci.yml
    parameters:
        BuildConfig: 'RelWithDebInfo'
        EnvSetupScript: setup_env_trt.bat
        buildArch: x64
        additionalBuildFlags: --enable_pybind --use_tensorrt --tensorrt_placeholder_builder --tensorrt_home="C:\local\TensorRT-8.4.1.5.Windows10.x86_64.cuda-11.6.cudnn8.4" --cuda_version=11.6 --cuda_home="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6" --cmake_extra_defines CMAKE_CUDA_ARCHITECTURES=52'
        msbuildPlatform: x64
        isX86: false
        job_name_suffix: x64_RelWithDebInfo
        RunOnnxRuntimeTests: ${{ parameters.RunOnnxRuntimeTests }}
        RunStaticCodeAnalysis: false
        ORT_EP_NAME: CUDA
        MachinePool: onnxruntime-Win2019-GPU
        ALLOW_RELEASED_ONNX_OPSET_ONLY: true